### ISSUE TITLE
how to raise the prompt efficiency

### ISSUE THREAD

**Issue by 77h2l** [chancharikmitra/CCoT#10]
thx for your work. since the scene graph need to be generated as the first step, and composition all inputs at the second step, though seem to be effective, the prompt costs raised, especially  when meeting super large size mllms, is there any trick to improve the efficiency for the prompt, maybe v2? 
:)

**Comment by chancharikmitra** [comment]
Hello, thanks for your interest in your work. The generation of the scene graph is a crucial part of the method. We do find relatively small scene graphs to work quite well, but nevertheless, there isn't a straightforward way to avoid the computational cost of generating the scene graph.

Here are some ideas though:

1. Lower the number of max tokens outputted.
2. Use few-shot prompting (with compact scene graph examples) or an instruction prompt that tells the LLM to keep the scene graph short.

Other than that, I imagine you would need architecture changes like sparse or linear attention. We leave this open to future work that we encourage you or others to pursue.

Hope this helps!
