### ISSUE TITLE
download link of dataset

### ISSUE THREAD

**Issue by ybx193670** [chancharikmitra/CCoT#4]
Could you please  provide a download link for the Seed-Bench-image dataset?

**Comment by chancharikmitra** [comment]
Hello! Thanks for your interest in our work. There is no separate download link for SEED-Bench image splits. We simply downloaded the image splits only for SEED-Bench-1, which can be found as part of the official dataset here: https://github.com/AILab-CVC/SEED-Bench

We _do_ provide a simple filtered jsonl of the questions for easy indexing of the data for our models, especially LLaVA.

Hope this helps!
