### ISSUE TITLE
use of sgPrompt

### ISSUE THREAD

**Issue by Gavin001201** [chancharikmitra/CCoT#5]
I noticed that  the "sgPrompt" is repeated twice when prompting the model to generate the scene graph. Is this because it can achieve better results?

**Comment by chancharikmitra** [comment]
So, our method, while broken into two inference call, only uses the scene graph generation prompt once. If you look at the code closely, you will notice that the first inference call generates the scene graph. The second call extracts the answer in the task format. You can check out the main figure in the paper for more details as well.

Hope this helps!

**Comment by Gavin001201** [comment]
> I noticed that the "sgPrompt" is repeated twice when prompting the model to generate the scene graph. Is this because it can achieve better results?

I mean that, in the first inference call, the "sgPrompt" was repeated twice:
![111](https://github.com/user-attachments/assets/b33f5689-b5d4-413c-8684-6b39dd9283e9)
![333](https://github.com/user-attachments/assets/4fa34fa3-94a3-49ee-a8d9-3fa5a90e13f7)

'<image>\nDoes the given caption accurately describe the given image? Caption:a young person kisses an old person.\n\n\n**For the provided image and its associated question, generate a scene graph in JSON format that includes the following:\n1. Objects that are relevant to answering the question\n2. Object attributes that are relevant to answering the question\n3. Object relationships that are relevant to answering the question\n\nScene Graph:**\n\n**For the provided image and its associated question, generate a scene graph in JSON format that includes the following:\n1. Objects that are relevant to answering the question\n2. Object attributes that are relevant to answering the question\n3. Object relationships that are relevant to answering the question\n\nScene Graph:**\n'
@chancharikmitra

**Comment by Gavin001201** [comment]
![222](https://github.com/user-attachments/assets/09d25cb3-9d94-44da-a173-99f7b31cb33c)
