### ISSUE TITLE
reason for scene graph

### ISSUE THREAD

**Issue by ybx193670** [chancharikmitra/CCoT#6]
Why you can avoid training and forgetting by inducting scene graph

**Comment by chancharikmitra** [comment]
Thanks for your interest in our work! So the reason for this is that CCoT is applied _at test time in the prompt_. None of the model weights are finetuned or adapted in any way. One challenge in the field is learning new tasks without forgetting the base pretraining which is what can oftentimes happen when you finetune a model, changing its underlying weights.

This is one of the major upsides of using CCoT in a light-weight, test-time manner for any model, without having to change any weights.

Hope this helps! Let us know if you have any more questions.

**Comment by ybx193670** [comment]
> 感谢您对我们工作的关注！因此，这样做的原因是 CCoT_在测试时应用于提示_。模型权重均未经过任何微调或调整。该领域的一个挑战是学习新任务而不忘记基础预训练，这通常是在微调模型时发生的情况，从而改变其底层权重。
> 
> 这是对任何模型以轻量级、测试时间方式使用 CCoT 的主要优点之一，无需更改任何权重。
> 
> 希望这能有所帮助！如果您还有其他问题，请告诉我们。

thanks for your reply
