### ISSUE TITLE
CCOT's positioning function

### ISSUE THREAD

**Issue by ybx193670** [chancharikmitra/CCoT#7]
Can the CCOT proposed in this article locate and describe the referent in the image based on an image and a command that requires inference? If so, how?

**Comment by chancharikmitra** [comment]
Hello! Thanks for your interest in our work. CCoT is a very flexible prompting method and based on our results, is useful for a variety of vision-language tasks. I anticipate it can be helpful for the language grounding task you mention. Trying it out on any LMM of your choice is quite easy by following the two-step prompting method in our paper: there isn't a limit to what architecture it can be applied to. To summarize, CCoT consists of a two-step, zero-shot prompt (i.e. no example necessary; but you can experiment with adding few-shot examples). The first prompt generates a SG given the image and task, while the second prompt extracts the answer/response to the task.

Hope this helps! Feel free to reopen the issue if you have further questions.
