### ISSUE TITLE
evaluation process on the Winoground dataset

### ISSUE THREAD

**Issue by aidialogue** [chancharikmitra/CCoT#8]
Hello! I would like to ask if the ans_path mentioned in eval_winoground.py refers to the result_path in GPT4V_wino.py, where each line is formatted as {"text": "Yes, the given caption accurately describes the given image. The image shows..."}. Is there any additional processing involved? In wino.py, does expain1 = result1["answer"] refer to the text in the result_path output of GPT4V_wino.py? 
2.does the qs_path in eval_winoground.py refer to parsed_winoground.jsonl? 
Thank you very much for your assistance!

**Comment by Brandon3964** [comment]
1. Yes, it's the output file. And "text" should be the same as "answer". This is a bug and thanks for pointing that out.
2. Yes.

**Comment by Brandon3964** [comment]
1. Yes, it's the output file. And "text" should be the same as "answer". This is a bug and thanks for pointing that out.

2. Yes.
