### ISSUE TITLE
About Whoops! dataset metric script.

### ISSUE THREAD

**Issue by ligeng0197** [chancharikmitra/CCoT#9]
Hello, thank you very much for your creative work on scene graph based prompting. We are trying to build upon your exciting work for further research. However, we noticed that the Whoops! dataset does not provide the corresponding metric calculation script. Could you briefly introduce the method for calculating specific metrics?

**Comment by Brandon3964** [comment]
Hi, thank you for building upon our work!

I believe [Whoops](https://whoops-benchmark.github.io/) provides the evaluation script under "Task Evaluation". What we used is "VQA: BEM Calculation". We slightly modified the script to make it easier to use and is attached below.
[Score_whoops.zip](https://github.com/user-attachments/files/17480125/Score_whoops.zip)

Hope this is helpful!
